name: ❓ Question
description: Ask a question
title: "❓ [Question] - <title>"
labels: Question
body:
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/euphony-io/euphony-hub-collector/issues) and [discussions](https://github.com/euphony-io/euphony-hub-collector/discussions) to see if a similar question already exists.
      options:
        - label: >
            I have searched the [issues](https://github.com/euphony-io/euphony-hub-collector/issues) and [discussions](https://github.com/euphony-io/euphony-hub-collector/discussions) and found no similar questions.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: What is your question?
      placeholder: |
        Include as much information as possible to receive the most helpful response.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra information
      description: screenshots, logs, tracebacks etc.
      placeholder: |
        Include as much information as possible to receive the most helpful response.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything Else?
      description: Anything else you would like to share?
